# Generated by Django 5.0.4 on 2024-04-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workingcode", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
