# Generated by Django 5.0.4 on 2024-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workingcode", "0002_alter_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
